#!/bin/bash
# Wiki Ingest Script - AI Enhanced Version
# Raw 폴더의 파일을 읽고 Wiki에 지능적으로 정리

VAULT="/home/comage/obsidian-vault/06-Wiki-시스템"
RAW="$VAULT/Raw"
WIKI="$VAULT/Wiki"
LOGS="$VAULT/Logs"
CLAUDE_MD="$VAULT/클로드.md"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE=$(date '+%Y-%m-%d')
LOG_FILE="$LOGS/${DATE}-ingest.log"

echo "[$TIMESTAMP] 📥 Wiki 인제스트 시작" | tee -a "$LOG_FILE"

# Raw 폴더가 비어있으면 종료
if [ -z "$(ls -A "$RAW" 2>/dev/null)" ]; then
    echo "[$TIMESTAMP] ⚠️ Raw 폴더가 비어있음 - 종료" | tee -a "$LOG_FILE"
    exit 0
fi

# 처리할 파일 목록
files=()
for file in "$RAW"/*.md "$RAW"/*.txt; do
    [ -f "$file" ] && files+=("$file")
done

if [ ${#files[@]} -eq 0 ]; then
    echo "[$TIMESTAMP] ⚠️ 처리할 파일 없음" | tee -a "$LOG_FILE"
    exit 0
fi

echo "[$TIMESTAMP] 📁 처리 대상: ${#files[@]}개 파일" | tee -a "$LOG_FILE"

# 각 Raw 파일 처리
new_docs=0
updated_docs=0
for file in "${files[@]}"; do
    filename=$(basename "$file")
    echo "" | tee -a "$LOG_FILE"
    echo "[$TIMESTAMP] 📄 처리 중: $filename" | tee -a "$LOG_FILE"
    
    # 파일 내용 읽기
    content=$(cat "$file")
    
    # 제목을 추출
    title=$(echo "$content" | grep -m1 '^#' | sed 's/^#*\s*//' | head -c 100)
    [ -z "$title" ] && title="${filename%.txt}"
    
    # 태그 추출
    tags=$(echo "$content" | grep -oE '#[a-zA-Z0-9가-힣]+' | sort -u | tr '\n' ' ')
    [ -z "$tags" ] && tags="#새문서"
    
    # 날짜 추출
    date_in_file=$(echo "$content" | grep -m1 '^[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -c 10)
    [ -z "$date_in_file" ] && date_in_file="$DATE"
    
    # URL 추출 (출처)
    urls=$(echo "$content" | grep -oE 'https?://[^[:space:]]+' | head -5)
    
    # 핵심 키워드 추출
    keywords=$(echo "$content" | tr ' ' '\n' | grep -E '^[A-Za-z가-힣]{2,15}$' | sort | uniq -c | sort -rn | head -8 | awk '{print $2}' | tr '\n' ', ')
    
    # Wiki 문서 생성
    wiki_filename="${filename%.txt}.md"
    
    # 이미 Wiki에 있는지 확인
    if [ -f "$WIKI/$wiki_filename" ]; then
        echo "[$TIMESTAMP] 🔄 기존 문서 업데이트: $wiki_filename" | tee -a "$LOG_FILE"
        
        # 기존 문서에 내용 추가
        {
            echo ""
            echo "---" 
            echo "## [$TIMESTAMP] 업데이트"
            echo "" 
            echo "### 추가된 내용"
            echo "$content" | head -30 | tail -n+2
            echo "" 
            echo "### 태그"
            echo "$tags"
            echo "" 
            echo "### 출처"
            echo "$urls" || echo '원본 파일 참조'
        } >> "$WIKI/$wiki_filename"
        
        # 업데이트됨 태그 추가
        sed -i 's/#새문서/#업데이트됨/g' "$WIKI/$wiki_filename"
        updated_docs=$((updated_docs + 1))
    else
        echo "[$TIMESTAMP] ✨ 새 문서 생성: $wiki_filename" | tee -a "$LOG_FILE"
        
        cat > "$WIKI/$wiki_filename" << WIKIEOF
# $title

## 기본 정보
- **원본 파일:** [[Raw/$filename]]
- **생성일:** $TIMESTAMP
- **최종 업데이트:** $TIMESTAMP
- **태그:** $tags

## 날짜
$date_in_file

## 핵심 키워드
$keywords

## 요약
$(echo "$content" | head -10 | tail -n+2 | sed 's/^/>/')

## 상세 내용
$(echo "$content" | head -50 | tail -n+2)

## 출처
$(echo "$urls" | sed 's/^/- /') || echo '- 원본 파일 참조'

## 관련 문서
<!-- 이 섹션은 수동으로 또는 Lint 과정에서 채워집니다 -->

---

*Auto-generated by Hermes Wiki System ($TIMESTAMP)*
WIKIEOF
        new_docs=$((new_docs + 1))
    fi
done

# 인덱스 업데이트
echo "" | tee -a "$LOG_FILE"
echo "[$TIMESTAMP] 📋 인덱스 업데이트 중..." | tee -a "$LOG_FILE"

INDEX_FILE="$WIKI/인덱스.md"
cat > "$INDEX_FILE" << INDEXEOF
# Wiki 인덱스

## 개요
이 파일은 Wiki 시스템의 모든 문서를 색인합니다.
**마지막 업데이트:** $TIMESTAMP

## 📊 통계
- 총 문서 수: $((new_docs + updated_docs))
- 새 문서: $new_docs
- 업데이트: $updated_docs

## 📁 문서 목록

INDEXEOF

count=0
for file in $(find "$WIKI" -name "*.md" | sort); do
    [ "$(basename "$file")" = "인덱스.md" ] && continue
    title=$(head -1 "$file" | sed 's/^#*\s*//')
    tags=$(grep -oE '#[a-zA-Z0-9가-힣]+' "$file" | sort -u | tr '\n' ' ')
    echo "- [[$(basename "$file" .md)]] $tags" >> "$INDEX_FILE"
    count=$((count + 1))
done

echo "" >> "$INDEX_FILE"
echo "## 🏷️ 태그별 문서" >> "$INDEX_FILE"

# 태그별 인덱스
for tag in $(find "$WIKI" -name "*.md" -exec grep -ohE '#[a-zA-Z0-9가-힣]+' {} \; | sort -u); do
    echo "" >> "$INDEX_FILE"
    echo "### $tag" >> "$INDEX_FILE"
    for file in $(find "$WIKI" -name "*.md"); do
        [ "$(basename "$file")" = "인덱스.md" ] && continue
        if grep -q "$tag" "$file"; then
            title=$(head -1 "$file" | sed 's/^#*\s*//')
            echo "- [[$(basename "$file" .md)]]" >> "$INDEX_FILE"
        fi
    done
done

echo "" >> "$INDEX_FILE"
echo "**총 문서:** $count개" >> "$INDEX_FILE"
echo "**인덱스 생성:** $TIMESTAMP" >> "$INDEX_FILE"

# 로그 업데이트
LOG_MD="$LOGS/${DATE}-log.md"
{
    echo "# $DATE 작업 로그"
    echo ""
    echo "## Ingest 결과"
    echo "- 시간: $TIMESTAMP"
    echo "- 새 문서: $new_docs"
    echo "- 업데이트: $updated_docs"
    echo "- 처리된 파일: ${#files[@]}"
    echo ""
} >> "$LOG_MD"

echo "" | tee -a "$LOG_FILE"
echo "[$TIMESTAMP] ✅ Wiki 인제스트 완료!" | tee -a "$LOG_FILE"
echo "   📄 새 문서: $new_docs" | tee -a "$LOG_FILE"
echo "   🔄 업데이트: $updated_docs" | tee -a "$LOG_FILE"
echo "   📊 총 문서: $count" | tee -a "$LOG_FILE"
